# Generated by Django 4.2.16 on 2025-06-04 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0028_brand_series_attributeoption_option_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductActiveOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.attributeoption', verbose_name='Значение опции')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.option', verbose_name='Опция')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_active_options', to='catalogue.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Опция продукта',
                'verbose_name_plural': 'Опции продукта',
                'abstract': False,
                'unique_together': {('product', 'option', 'attribute_option')},
            },
        ),
    ]
