version: '3.8'

services:
  web:
    build: 
      context: ./valentishop
      dockerfile: dockerfile.prod
    image: 891377337328.dkr.ecr.eu-north-1.amazonaws.com/valenti:web
    command: gunicorn valentishop.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
      - solr_data:/opt/solr
    expose:
      - 8000
    env_file:
      - ./.env.prod
    networks:
      - web
  nginx-proxy:
    container_name: nginx-proxy
    build: nginx
    image: 891377337328.dkr.ecr.eu-north-1.amazonaws.com/valenti:nginx-proxy
    restart: always
    ports:
      - 443:443
      - 80:80
    volumes:
      - static_volume:/home/valentishop/web/staticfiles
      - media_volume:/home/valentishop/web/mediafiles
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - web

  acme-companion:
    image: nginxproxy/acme-companion
    env_file:
      - ./.env.prod.proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - acme:/etc/acme.sh

  solr:
    container_name: solr
    image: solr:6.6.6
    restart: always
    ports:
     - 8983:8983
    volumes:
      - solr_data:/opt/solr
    networks:
      - web


volumes:
  static_volume:
  media_volume:
  certs:
  html:
  vhost:
  acme:
  solr_data:
networks:
  web: