version: '3.8'

services:
  web:
    build: ./valentishop
    command: gunicorn valentishop.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./valentishop/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
