from oscar.apps.catalogue.categories import create_from_breadcrumbs

categories = [
"footwear>sport>running",
"footwear>casual>sneakers",
"footwear>casual>sport",
"footwear>sport>basketball",
"footwear>casual>vintage_basketball",
"footwear>sport>soccer",
"footwear>casual>daddy",
"footwear>sport>hikking",
"footwear>sport>training",
"footwear>casual>canvas",
"footwear>sport>outdoor",
"footwear>sport>tennis",
"footwear>sport>badminton",
"apparel>featured_jacket>jacket",
"apparel>featured_jacket>down_jacket",
"footwear>boots>snow",
"accessories>hat>peaked_cap",
"footwear>boots>outdoor",
"footwear>boots>martin",
"apparel>featured_jacket>cotton_clothes",
"accessories>bags>diagonal_bag",
"accessories>hat>fleece",
"footwear>boots>short",
"apparel>featured_tops>hoodie",
"apparel>featured_tops>vest",
"apparel>featured_tops>t_shirt",
"apparel>pants>jeans",
"footwear>slippers>sport_sandals",
"apparel>featured_tops>sweater",
"accessories>glasses>optical_frame",
"footwear>sport>martin_boots",
"footwear>casual>running",
"accessories>bags>backpack",
"accessories>jewelry>necklace",
"apparel>pants>cargo",
"accessories>glasses>sunglasses",
"accessories>bags>tote",
"footwear>slippers>sport",
"apparel>featured_tops>shirt",
"brand >New Balance",
"brand >Nike",
"brand >adidas originals",
"brand >Jordan",
"brand >Asics",
"brand >UGG",
"brand >Mizuno",
"brand >Vans",
"brand >李宁",
"brand >adidas neo",
"brand >SALOMON/萨洛蒙",
"brand >OSIRIS",
"brand >adidas",
"brand >Reebok",
"brand >Feng Chen Wang",
"brand >Kappa",
"brand >Converse",
"brand >PUMA",
"brand >Onitsuka Tiger",
"brand >顽刻ollieskate",
"brand >OLD ORDER",
"brand >安踏",
"brand >Under Armour",
"brand >Columbia",
"brand >361°",
"brand >clarks",
"brand >Skechers/斯凯奇",
"brand >On昂跑",
"brand >EBLAN",
"brand >OFF-WHITE",
"brand >Native Shoes",
"brand >KENZO",
"brand >中国李宁",
"brand >saucony",
"brand >Y-3",
"brand >Timberland",
"brand >palladium",
"brand >Balenciaga",
"brand >HOKA ONE ONE",
"brand >FILA FUSION",
"brand >A BATHING APE",
"brand >RIFUGIO VO'",
"brand >Oakley/欧克利",
"brand >JEEP SPIRIT",
"brand >ecco/爱步",
"brand >北面/THE NORTH FACE",
"brand >Supreme",
"brand >CAMEL骆驼",
"brand >MICHAEL KORS 迈克高仕",
"brand >Moncler",
"brand >GOBLIN SHARKS 1759",
"brand >GAP",
"brand >STONE ISLAND",
"brand >Boy London",
"brand >levi’s",
"brand >ROUTE 66",
"brand >UNTILWERICH",
"brand >DR.MARTENS",
"brand >MIND ERROR",
"brand >PSO Brand",
"brand >SAINT LAURENT/圣罗兰",
"brand >马登 MADEN",
"brand >Warrior/回力",
"brand >Burberry",
"brand >CHARLES&KEITH",
"brand >GOLFCROSS",
"brand >A SQUARE ROOT/A 的平方根",
"brand >cooraree",
"brand >YEEZY",
"brand >MUVA",
"brand >LAMLICKA",
"brand >EQLZ",
"brand >THEWIZBRAND"
    ]

for breadcrumbs in categories:
    create_from_breadcrumbs(breadcrumbs)

print("categories creates succesufely")